# Generated by Django 3.0.7 on 2020-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
